# Generated by Django 4.0.2 on 2022-03-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_careers_job_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default='', upload_to='applicant_resumes/'),
            preserve_default=False,
        ),
    ]
