# Generated by Django 4.0.2 on 2022-03-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='num_applications',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
