# Generated by Django 4.0.2 on 2022-03-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='num_applications',
            field=models.IntegerField(default=0),
        ),
    ]
