# Generated by Django 4.0.2 on 2022-03-01 06:23

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('type', models.CharField(choices=[('Staff', 'Staff'), ('Startup', 'Startup'), ('Mentor', 'Mentor')], default='Staff', max_length=20)),
                ('terms_and_conditions_confirmed', models.BooleanField(default=0)),
                ('profile_pic', models.ImageField(default='null', upload_to='images/')),
                ('approved', models.BooleanField(default=False)),
                ('profile_locked', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='emailOTP',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='null', max_length=20)),
                ('place', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('whatsappnumber', models.CharField(max_length=15)),
                ('profilepic', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.CharField(max_length=255)),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('post_photo', models.ImageField(upload_to='post_images/')),
                ('like_count', models.CharField(default=0, max_length=255)),
                ('comment_count', models.CharField(default=0, max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.user_posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('like_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('comment_content', models.TextField()),
                ('comment_time', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartupCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=255)),
                ('registration_year', models.CharField(default='', max_length=255)),
                ('date_of_incubation', models.CharField(default='', max_length=255)),
                ('type_of_incubation', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('operational_model', models.TextField()),
                ('target_market', models.CharField(max_length=255)),
                ('cin_number', models.CharField(max_length=255)),
                ('dipp_number', models.CharField(max_length=255)),
                ('founder', models.CharField(max_length=255)),
                ('num_directors', models.CharField(max_length=255)),
                ('num_women_dir', models.CharField(max_length=255)),
                ('stage', models.CharField(max_length=255)),
                ('employees', models.CharField(max_length=255)),
                ('webpage', models.CharField(max_length=255)),
                ('msme_registration', models.CharField(max_length=255)),
                ('flagship_program', models.CharField(max_length=255)),
                ('nature_of_firm', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('intelectual_property', models.BooleanField(default=False)),
                ('i_property_type', models.CharField(max_length=255)),
                ('number_of_ip', models.CharField(max_length=10)),
                ('funding', models.CharField(max_length=255)),
                ('academic_qualification_founder', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('experience_of_founder', models.CharField(max_length=255)),
                ('core_competancy', models.CharField(max_length=255)),
                ('expectation', models.TextField()),
                ('company_logo', models.FileField(upload_to='company_logo/')),
                ('startup_pitch', models.FileField(upload_to='pitch/')),
                ('about', models.TextField()),
                ('other_info', models.TextField()),
                ('applied_for_incubation', models.BooleanField(default=False)),
                ('contract_date', models.DateField(default='')),
                ('contract_expiry', models.DateField(default='')),
                ('contract_pdf', models.FileField(upload_to='startups_contract/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorInfo',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=100)),
                ('Current_working_company', models.CharField(max_length=100)),
                ('Previous_working_experience', models.TextField()),
                ('supported_any_startup', models.BooleanField(default=False)),
                ('Working_Domain', models.CharField(max_length=100)),
                ('areas_of_expertise', models.CharField(max_length=255)),
                ('Presently_residing', models.TextField()),
                ('Bachelors_Degree', models.BooleanField(default=False)),
                ('Masters_Degree', models.BooleanField(default=False)),
                ('PHD', models.BooleanField(default=False)),
                ('B_Institute', models.CharField(max_length=255)),
                ('M_Institute', models.CharField(max_length=255)),
                ('P_Institute', models.CharField(max_length=255)),
                ('B_Subject', models.CharField(max_length=255)),
                ('M_Subject', models.CharField(max_length=255)),
                ('P_Subject', models.CharField(max_length=255)),
                ('experience_as_mentor', models.CharField(default='null', max_length=255)),
                ('contribution_to_startup_echosystem', models.TextField(default='null')),
                ('post_doctorate', models.BooleanField(default=False)),
                ('post_doctorate_domain', models.CharField(default='null', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField()),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.user_comments')),
            ],
        ),
    ]
