# Generated by Django 4.0.2 on 2022-03-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupcompanyinfo',
            name='contract_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='startupcompanyinfo',
            name='contract_expiry',
            field=models.CharField(max_length=255),
        ),
    ]
