# Generated by Django 4.0.2 on 2022-03-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_startupcompanyinfo_contract_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupcompanyinfo',
            name='contract_pdf',
            field=models.FileField(upload_to='contracts/'),
        ),
    ]
