# Generated by Django 4.0.2 on 2022-03-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_alter_startupcompanyinfo_contract_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
